[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "SneakerSeeker"
version = "1.0.0.0"

[tool.setuptools]
py-modules = ["sneaker_seeker"]

[project.scripts]
ssgame = "sneaker_seeker.__main__:main"